[package]
name = "planout"
version = "0.1.0"
authors = ["nconnor <nicholas.k.connor@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
