[package]
name = "planout"
version = "0.1.0"
authors = ["nconnor <nicholas.k.connor@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
pest = "2"
pest_derive  = "2"

[dev-dependencies]
